# Generated by Django 4.2.20 on 2025-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_playlist_playlistmusic"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playlistmusic",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="playlistmusic",
            name="music",
        ),
        migrations.AddField(
            model_name="playlistmusic",
            name="music",
            field=models.ManyToManyField(to="item.music"),
        ),
    ]
