# Generated by Django 4.2.20 on 2025-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_playlistmusic_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="playlist",
            name="music",
            field=models.ManyToManyField(to="item.music"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="PlaylistMusic",
        ),
    ]
