# Generated by Django 4.2.20 on 2025-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_alter_playlist_options_playlist_music_playlist_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="music",
            field=models.ManyToManyField(blank=True, null=True, to="item.music"),
        ),
    ]
