# Generated by Django 4.2.20 on 2025-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_rename_name_playlist_title_alter_playlist_music"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
